### ISSUE TITLE
Feature request: Option to pull blacklist words rather than custom enter into an env var

### ISSUE THREAD

**Issue by michael-leon** [hijxf/lastfm2slack#10]
**Is your feature request related to a problem? Please describe.**
When I put in blacklist words, I always forget about some words and it results in embarrassing/not-exactly-HR-friendly Slack statuses appearing.

**Describe the solution you'd like**
Provide an option to pull a wordlist from GitHub [potential one here?](https://github.com/snguyenthanh/better_profanity/blob/master/better_profanity/profanity_wordlist.txt) and use that as your blacklist words.

**Describe alternatives you've considered**
Spending time formatting a word list from GitHub into the environment variable format.

**Additional context**

**Comment by hijxf** [comment]
Great idea! I'll get working on this and keep this issue posted.
